// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'src/models/todo';

export const models = {
model_1: { namespace: 'todo', model: model_1 },
} as const
