// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { lazy } from "react";
          const routes = [{ path: '/about', component: lazy(async () => {
              return await import('../pages/about/index.tsx');
            })},{ path: '/model', component: lazy(async () => {
              return await import('../pages/model/index.tsx');
            })},{ path: '/home', component: lazy(async () => {
              return await import('../pages/home/index.tsx');
            })}];
          export default routes;
